### ISSUE TITLE
[Request] Port for 1.19.2

### ISSUE THREAD

**Issue by Terminal-Access** [sa-shiro/Minecraft-Compressed-Blocks#16] opened 2022-08-29 12:14 UTC
Just wanted to leave a little bit of support here thanks for this mod im loving it, as well as politely asking for a bump/port over to 1.19.2 thanks!

**Comment by sa-shiro** [comment] 2022-09-26 21:33
added all missing items with b778f7d58956d5042e8741e2cfaa3e62e8237de9
update to 1.19 will follow soon, i am sorry for this late response, but i was pretty busy

**Comment by sa-shiro** [comment] 2022-09-27 00:16
No need to build it on your own, will be automatically pushed to curseforge marked as alpha version.

**Comment by Terminal-Access** [comment] 2022-09-27 14:32
compressedblocks Version:  1.1.0.20220926
ServerVersion Paper: paper-1.19.2-175

Awesome work on the update thanks for getting back to us with this.

Unfortunatly it's crashing when being loaded witrh the following error, loks to be a malformed/missing plugin.yml file.

`[15:24:03 ERROR]: Could not load 'plugins\[1.19.2]compressedblocks-1.1.0.20220926.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.2.jar:git-Paper-175]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.2.jar:git-Paper-175]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-175]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-175]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 7 more`

**Comment by sa-shiro** [comment] 2022-09-27 14:39
Oh well, I hadn't a crash within the dev environment,  ill have a look at this in some minutes when I get home!

**Comment by sa-shiro** [comment] 2022-09-27 14:42
Is it possible that you post the entire log file / error or debug log?

**Comment by sa-shiro** [comment] 2022-09-27 14:56
`[..] paper-api [...] `

Oh i think i see what the issue is..
You are trying to load it as a plugin on the paper server, this is (currently) not possible as this is a pure forge mod, hence requires a forge server or a paper bridge that is able to load forge mods

**Comment by Terminal-Access** [comment] 2022-09-27 18:56
Ahh my apologies i must have gotten this mod mixed up with a simlaer plugin I was using, apologies.

**Comment by sa-shiro** [comment] 2022-09-27 18:57
Ah, don't sorry such things can happen ^^

**Closed** 2022-11-19 17:10 UTC
Labels: suggestions
